# Language/versions
language: node_js
node_js:
  - "4.1.x"
  - "4.0.x"
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"

# Build script
script: 'mocha -ig "amqp server"'

# Notifications
notifications:
 email:
   - notify+mail@tedeh.net
