# Language/versions
language: node_js
node_js:
  - "iojs"
  - "0.12"
  - "0.11"
  - "0.10"

# Build script
script: 'mocha -ig "amqp server"'

# Notifications
notifications:
 email:
   - notify+mail@tedeh.net
